[workspace]
members = ["contracts", "verifier"]

[workspace.package]
version = "0.1.0"
edition = "2024_07"

[workspace.dependencies]
assert_macros = "2.9.1"
cairo_test = "2.9.1"
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.15.3" }
openzeppelin = "0.20.0"
snforge_std = "0.35.1"
starknet = "2.9.1"

[cairo]
sierra-replace-ids = false
